### ISSUE TITLE
Set String alias for Currency Names

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/btcpayserver-boltz#10]
Can't use currency names like `Btc` or `liquid` directly, as we need to capitalize them differently. Please use strings.

![image](https://github.com/user-attachments/assets/27f9ba81-cb71-428e-beb1-d53123ee815f)

**Comment by kilrau** [comment]
![image](https://github.com/user-attachments/assets/c23a00d1-234a-473b-8ed9-175bcab7c98c)

**Comment by kilrau** [comment]
![image](https://github.com/user-attachments/assets/6c11f888-75f8-47bc-a7d7-ee257203ac53)

**Comment by jackstar12** [comment]
so which values do we want? mainchain / liquid or BTC / L-BTC?

**Comment by kilrau** [comment]
We want a string that I can change. But if easier go with `BTC` & `L-BTC`
