### ISSUE TITLE
Setup doesn't recognize internal Lightning node connected at runtime

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/btcpayserver-boltz#17]
I created a fresh store, first did *not* connect it to the internal lightning node. Ran Boltz Setup, it correctly recognized that Lighting node "not available", closed setup, connected the lightning node, openend setup again -> still in state "not available"

![image](https://github.com/user-attachments/assets/f77a24a3-73e6-4238-bc77-a2ed6f2912d8)

**Comment by kilrau** [comment]
Hmm it doesn't recognize the node at all if I connect it at runtime, need to restart btcpay server for it to get recognized. Not high prio but can we recognize the Lightning node at runtime?

**Comment by jackstar12** [comment]
what do you mean with connect at runtime? configure it as the node in your current store? thats not connecting at runtime, which btcpay doesnt support
