### ISSUE TITLE
Setup should have standalone mode greyed out when node connected

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/btcpayserver-boltz#18]
We are currently just overwrite the connection to an existing node without warning. I'd highly recommend we grey out and let the user manually disconnect. So it'll only ever be one of the two options available. Adjusted figma.

As-is:
![image](https://github.com/user-attachments/assets/580f69df-c469-4286-8189-bd19f08fcda9)

Should be:
![image](https://github.com/user-attachments/assets/d330c0f8-c909-4347-aa06-65d899d526af)
![image](https://github.com/user-attachments/assets/96305173-fb2b-4e80-9ba2-d3fae01f71cf)

**Comment by jackstar12** [comment]
what if the connected node is of type boltz?

**Comment by kilrau** [comment]
> what if the connected node is of type boltz?

Then we allow, this issue is only about blocking *external* node connections
