### ISSUE TITLE
Review Round 1

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/btcpayserver-boltz#2]
# General:
- [x] Full Screen Setup close (x) doesn't work when opening setup for first time, remove x  button as setup can't be closed unless fully configured once
- [x] Bring Full Screen Setup until one option was fully configured
- [x] Show Lightning Balances in Dashboard
- [x] Boltz icon needs thicker circle line
![image](https://github.com/user-attachments/assets/ef4269f9-1eb5-43c4-b828-5da1e898d5c0)
- [ ] Input validation missing practically on all input fields
![image](https://github.com/user-attachments/assets/c512022e-7423-4e24-b508-060a62ed9c99)

# Nodeless:
- [ ] If I enter Setup, e.g. via BTCPay -> Wallets -> Lightning and immediately exit, UI behaves as if I successfully configured nodeless mode, shows plugin info/configuration/admin page and also shows a "Boltz Wallet" 
![image](https://github.com/user-attachments/assets/6010935e-2454-454b-bd4e-edb35a6ab62b)
- [ ] Once Boltz indeed is successfully configured, let's stick with the same button but *add* a sentence below: "Boltz was successfully configured. and a button "Boltz Dashboard"
- [x] When I click on "Configure Boltz" it should show me a one-liner explaining what this is with a button "Setup" instead of jumping directly into the setup flow. These buttons should behave like "tabs" in this UI. 
[Screencast from 07-22-2024 04:47:02 PM.webm](https://github.com/user-attachments/assets/9b73f8b1-0859-4014-97e0-aff1e9186a01)
- [x] Since this is confusing and the only use case I can imagine is connecting to an externally running Boltz Client for nodeless node, I'd just remove this for now and only keep the "Configure Boltz" button.
![image](https://github.com/user-attachments/assets/25d0a320-f1ea-48c0-b30b-5a426ac0634e)
If an advanced user wants to connect to an external client, this still can be done by first setting it and then BTCPay Wallets -> Lightning -> Settings -> Change connection
- [ ] Fix missing currency when saving lightning config with a liquid wallet
- [x] Widget shows Lightning disabled and Chain running, guess that's just the autoswap status each. I'd simply show Lightning enabled and nothing else for nodeless

# Rebalance:

**Comment by jackstar12** [comment]
> [ ] BTCPay dashboard shows this, it should show "Liquid" balance

not possible

**Comment by kilrau** [comment]
Could you update this issue? @jackstar12
