### ISSUE TITLE
Default chain swap amount threshold

### ISSUE THREAD

**Issue by kilrau** [BoltzExchange/btcpayserver-boltz#9]
Should be 10 million sats (0.1 BTC) 
![image](https://github.com/user-attachments/assets/dd542ace-befd-4581-af9e-bacf20a336cd)

**Comment by jackstar12** [comment]
Its currently the min swap amoutn + 10k sats buffer, just like cli

**Comment by kilrau** [comment]
cli autoswap setup doesn't have a default for chain swaps theshold

![image](https://github.com/user-attachments/assets/bb25b3e8-c7d5-4f28-b3ca-7b9500430944)

**Comment by jackstar12** [comment]
Ah, its only the minimum required value there.

**Comment by kilrau** [comment]
Yep, got that. Please change it to 10 million sats as this is a more realistic value merchants would want to set.
